language: python

python:
  - "3.7"

install:
 - pip install -r requirements.txt

services:
 - postgresql

before_script:
  - psql -c 'create database authorshaven;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script: 
 - tox

# Post coverage results to coverage.io
after_success:
  - coveralls
