language: python

python:
  - "3.6"

install:
 - pip install -r requirements.txt

services:
 - postgresql

before_script:
  - psql -c 'create database authorshaven;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script: 
 - coverage run --source=authors/apps manage.py test
 - python -m coverage report -m