# Generated by Django 2.1.5 on 2019-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_notification_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notification_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
